services:
  mysql:
    image: mysql:8
    env_file:
      - env/.${NODE_ENV}.env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    profiles:
      - local

  redis:
    image: bitnami/redis:7.2.1
    env_file:
      - env/.${NODE_ENV}.env
    environment:
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    profiles:
      - local

  pt-backend:
    image: pt-backend
    build:
      platforms:
        - ${PLATFORM}
      context: ./
      dockerfile: ./backend/Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
        API_PORT_0: ${API_PORT_0}
      tags:
        - ${REGISTRY_URL}/pt-backend-${NODE_ENV}:${TAG}
    env_file:
      - ./env/.${NODE_ENV}.env
    ports:
      - ${API_PORT_0}:${API_PORT_0}
    volumes:
      - ./env:/env
      - ./backend/certs:/app/certs
    restart: always
    depends_on: [ mysql, redis ]

  nginx:
    image: nginx
    restart: always
    ports:
      - "4433:4433"
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    volumes:
      - ./backend/templates/nginx.conf:/etc/nginx/templates/nginx.conf.template:ro
      - ./backend/certs:/etc/nginx/certs:ro
    env_file:
      - ./env/.${NODE_ENV}.env
    depends_on: [ pt-backend ]

  pt-frontend:
    image: pt-frontend
    build:
      platforms:
        - ${PLATFORM}
      context: ./
      dockerfile: ./frontend/Dockerfile
      args:
        ENV_NAME: ${ENV_NAME}
        HOST_URL: ${HOST_URL}
        FRONT_PORT_1: ${FRONT_PORT_1}
        FRONT_PORT_2: ${FRONT_PORT_2}
        API_PORT_3: ${API_PORT_3}
      tags:
        - ${REGISTRY_URL}/pt-frontend-${NODE_ENV}:${TAG}
    env_file:
      - env/.${NODE_ENV}.env
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    ports:
      - ${FRONT_PORT_0}:${FRONT_PORT_2}
    volumes:
      - ./env:/env
      - ./frontend/templates/nginx.conf:/etc/nginx/templates/nginx.conf.template
      - ./frontend/certs:/etc/nginx/certs
      - ./frontend/public:/public
    restart: always
    depends_on: [ mysql, redis, pt-backend ]

  mysql-test:
    image: mysql:8
    env_file:
      - env/.${NODE_ENV}.env
    container_name: mysql-test
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_TEST_PORT}:${DB_PORT}
    profiles:
      - test

  redis-test:
    image: bitnami/redis:latest
    env_file:
      - env/.${NODE_ENV}.env
    environment:
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
    container_name: redis-test
    ports:
      - ${REDIS_TEST_PORT}:${REDIS_PORT}
    profiles:
      - test

networks:
  default:
    driver: bridge
    name: pipe-timer
